project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story.urls')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

story/urls.py
from django.urls import path
from . import views
app_name = 'story'

urlpatterns = [
    path('', views.story_list, name='story_list'),
    path('<slug:category_slug>', views.story_list, name="story_category"),
    path('<int:id>/', views.story_detail, name='story_detail'),
    path('search/', views.search_story, name='search_story'),
    path('tag/<slug:tag_slug>',views.story_list, name="story_by_tag"),
]

story/models.py
from django.db import models
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(unique=True)
    class Meta:
        ordering = ('-name',)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('story:story_category',args=[self.slug,])


class Story(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    body = CKEditor5Field('Body', config_name='extends')
    des = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('story:story_detail',args=[self.id,])

story/views.py
import random

from django.shortcuts import render, get_object_or_404
from . models import Story, Category
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.db.models import Q
from taggit.models import Tag



def story_list(request, category_slug=None, tag_slug=None):
    category = None
    categories = Category.objects.all()
    story = Story.objects.all()
    paginator = Paginator(story,2)
    page = request.GET.get('page')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,slug= tag_slug)
        story = Story.objects.filter(tags__in=[tag])
    try:
        story = paginator.page(page)
    except PageNotAnInteger:
        story = paginator.page( 1 )
    except EmptyPage:
        story = paginator.page(paginator.num_pages)
    if category_slug:
        story = Story.objects.all()
        category = get_object_or_404(Category, slug=category_slug)
        story = story.filter(category=category)
        paginator = Paginator(story,2)
        page = request.GET.get('page')
        try:
            story = paginator.page(page)
        except PageNotAnInteger:
            story = paginator.page(1)
        except EmptyPage:
            story = paginator.page(paginator.num_pages)
    all_story =Story.objects.all()
    recent_story = all_story[:3]
    if tag_slug:
        tag = get_object_or_404(Tag,slug= tag_slug)
        story = Story.objects.filter(tags__in=[tag])
    paginator = Paginator(story, 2)
    page = request.GET.get('page')
    try:
        story = paginator.page(page)
    except PageNotAnInteger:
        story = paginator.page(1)
    except EmptyPage:
        story = paginator.page(paginator.num_pages)
    return render(request, 'story/story_list.html', {'categories': categories,
                                                     'story': story,
                                                     'category': category,
                                                     'page': page,
                                                     'recent_story':recent_story,
                                                     'tag':tag,
                                                     })

def story_detail(request,id):
    story =get_object_or_404(Story, id=id)
    like_story =Story.objects.exclude(id=id)
    ### TAGS
    post_tags_ids = Story.tags.values_list('id', flat=True)
    similar_posts = Story.objects.filter(tags__in = post_tags_ids).exclude(id=story.id)
    similar_posts = similar_posts.annotate(same_tags = Count('tags')).order_by('-same_tags','-publish')[:2]

    return render(request, 'story/story_detail.html', {'story':story, 'like_story':like_story,
                                                       'similar_posts':similar_posts})

def search_story(request):
    query =None
    results =[]
    if request.method == "GET":
        query =request.GET.get("search")
        results =Story.objects.filter(Q(title__icontains =query)|Q(body__icontains =query))
    return render(request, 'story/search.html',{'query': query,'results':results})

story/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

   {% block title %} <title>story book</title>{% endblock %}
  </head>
  <body>
    <!-- As a heading -->
    <nav class="navbar navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Story book</span>
    </nav>
    {% block body %}

    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper)
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    -->
    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

story/templates/pagination.html
<div class="">
    <span class="">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="">
            Page {{page.number}} of {{page.paginator.num_pages}}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

story/templates/story/search.html
{% extends 'base.html'%}
{% block content %}
{% block title %}
Search story
{% endblock %}
{% block body %}
    <div class="container">
        <h1>This is search page</h1>
        {% if query %}
            <h3>{% with results.count as total_results %}
                Found {{total_results}} results
                {% endwith %}
            </h3>
            {% for x in results %}
                <div class="mt-3">
                    <a href="{{x.get_absolute_url}}">
                    <h2>{{ x.title }}</h2>
                    </a>
                    <p>{{ x.des }}</p>
                </div>
            {% empty %}
                <h3>There is no query</h3>
            {% endfor %}
        {% else %}
            <h3>Please search for a right query, you don't write any query</h3>
        {% endif %}
    </div>
{% endblock %}
{% endblock %}

story/templates/story/story_detail.html
{% extends 'base.html' %}
{% block title %}
<tile>{{ story.title }}</tile>
{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center">{{ story.title }}</h2>
        <p class="lead">{{ story.body | safe}}</p>
    </div>
    <hr>
    <div class="container">
        <h2>YOU MAY ALSO LIKE</h2>
        {% for x in like_story %}
        <a href="{{x.get_absolute_url}}">
            <h5>{{x.title}}</h5>
        </a>
        {% endfor %}
        <br>
        <h2>Similar posts</h2>
        {% for post in similar_posts %}
        <p>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </p>
        {% empty %}
        There are no similar story yet.
        {% endfor %}
    </div>
{% endblock %}

story/templates/story/story_list.html
{% extends 'base.html'%}
{% block content %}
{% block title %}
Story book
{% endblock %}
{% block body %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Story Book</h2>
    <p class="lead">You can find here some short stories</p>
</div>
<div class="container">
<div class="jumbotron mt-3">
    <h3>Categories</h3>
    <ul>
        <li>
            <a href = "{% url 'story:story_list' %}">All</a>
        </li>
        {% for x in categories %}
        <li>
            <a href="{{x.get_absolute_url}}"><h2>{{ x.name }}</h2></a>
        </li>
        {% endfor %}
    </ul>
</div>
<div>

    <form action="{% url 'story:search_story' %}" class="form_inline" method="get">
        <div class="form-group mb-2">
            <h3> {% if category %}{{category.name}}{% else %}ALL_STORY{% endif %}</h3>
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label class="sr-only">Search</label>
            <input name="search" class="form-control">
        </div>
        <button type="submit" class="btn btn-success btn-lg">Search</button>
    </form>
    {% for x in story %}
    <div class="mt-3">
        <a href="{{x.get_absolute_url}}">
            <h2>{{ x.title }}</h2>
        </a>
        Tag:{% for tag in x.tags.all %}
        <a href='{% url "story:story_by_tag" tag.slug %}'>
            {{tag.name}}
        </a>
        {% if not forloop.last %},{% endif %}
        {% endfor %}
        <p>{{ x.des }}</p>
    </div>
    {% endfor %}<hr>
    <h6 class="text-center">{% include "pagination.html" with page=story %}</h6>
        <hr>
        <h6>Recent three story</h6>
        {% for x in recent_story %}
            <a href="{{x.get_absolute_url}}">
            <h6>{{ x.title }}</h6>
            </a>
        {% endfor %}
</div>
</div>
{% endblock %}
{% endblock %}